apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 1h
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
  values:
    image:
      tag: "10.11.6"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-local
      media:
        enabled: true
        existingClaim: jellyfin-media
    securityContext:
      privileged: true
    resources:
      limits:
        nvidia.com/gpu: 1
    nodeSelector:
      gpu: "true"
    runtimeClassName: nvidia