apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 15Ti
  nfs:
    server: 10.0.10.20
    path: /mnt/tank/k3s/jellyfin-media
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: jellyfin-media
  resources:
    requests:
      storage: 15Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-local
  namespace: jellyfin
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 10Gi