---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: arr
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Phoenix"
          ports:
            - containerPort: 6767
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: media
          persistentVolumeClaim:
            claimName: arr-media

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: arr
  labels:
    app: bazarr
spec:
  selector:
    app: bazarr
  ports:
    - name: http
      port: 6767
      targetPort: http
      protocol: TCP
