apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "America/Phoenix"
          ports:
            - containerPort: 8191
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: arr
spec:
  selector:
    app: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191