apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.dozydelta.com`)
      kind: Rule
      middlewares:
        - name: ak-outpost-dozynet
          namespace: authentik
      services:
        - name: sonarr
          port: 8989
  tls:
    secretName: dozydelta-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.dozydelta.com`)
      kind: Rule
      middlewares:
        - name: ak-outpost-dozynet
          namespace: authentik
      services:
        - name: radarr
          port: 7878
  tls:
    secretName: dozydelta-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.dozydelta.com`)
      kind: Rule
      middlewares:
        - name: ak-outpost-dozynet
          namespace: authentik
      services:
        - name: prowlarr
          port: 9696
  tls:
    secretName: dozydelta-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.dozydelta.com`)
      kind: Rule
      middlewares:
        - name: ak-outpost-arr        # Authentik forward-auth, same as rest of arr stack
          namespace: arr
      services:
        - name: bazarr
          port: 6767
  tls:
    secretName: dozydelta-com-tls    # Reflector-mirrored wildcard cert