resources:
  - namespace.yaml
  - pvcs.yaml
  - bazarr-deployment.yaml
  - prowlarr-deployment.yaml
  - sonarr-deployment.yaml
  - radarr-deployment.yaml
  - flaresolvarr-deployment.yaml
  - ingress.yaml