apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-downloads
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 15Ti
  nfs:
    path: /mnt/tank/k3s/downloads
    server: 10.0.10.20
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-downloads
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  storageClassName: ""
  volumeName: arr-downloads
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 15Ti
  nfs:
    path: /mnt/tank/k3s/jellyfin-media
    server: 10.0.10.20
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-media
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  storageClassName: ""
  volumeName: arr-media
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-local
  namespace: arr
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-local
  namespace: arr
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-local
  namespace: arr
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
