apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-downloads
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: arr-downloads
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-media
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: arr-media
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-downloads
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.20
    path: /mnt/tank/k3s/downloads
  claimRef:
    namespace: arr
    name: arr-downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-media
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.20
    path: /mnt/tank/k3s/jellyfin-jellyfin-media-pvc-e6689025-aa9c-4fd3-b617-a935dae8638f
  claimRef:
    namespace: arr
    name: arr-media