apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dozydelta-wildcard
  namespace: kube-system
spec:
  secretName: dozydelta-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.dozydelta.com"
  dnsNames:
    - "*.dozydelta.com"
    - "dozydelta.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "jellyfin,authentik"