apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAB+gnxn+kb/quwh73Ofh7UApGokpB++RUfpJp4tqro5FAkUmeyP2G73Si4Wq3DHJSLwMyBW/Vt3U/EaT3XEgz/DP1HojV/mMQc+A29A4UZxzmnjXeXls4qKr4gBNUQ2Yo2he8rzzVJbbzYKSycuhQPW5OWWrJ/icyMQ3NoMzN4yADLYPg9EcbC1YUdajH9W++rR/8rHstMa2obeTbsvmnIxXujNSAxlGZUo4JsSX+wvu6Pu+jGqID0HvMGLeGiDGHMaj9PZkBFXQV/2ENBqLPeqeTbTr7j7a/Rjd+QgjaQ05Nvbl/9hbbu/9mgvZHNZbpFySNmvQgXTcYiqxKC1al3d8tIXl8ChcRaE9VngyTi12v72JmxHkty+XGRa7T1pEiTzhGGxWzgCF7IMuCDzCHUDeKJBMxEf5X0eIYVYDDjuynLPPtCiAcwwP/sMh06I+JPQd3Do6T26v4/JSxuUPZ6Huakoz923Ib1fQbkk22rAIGFmWQVOPrBotCycmtgwVLX8vQvjiIuVnSzcrY8OP0lN5tC36M5RdtQU8rW+kY9qJ5veyUm08/FnGJGIfNY9iBHZgJXRIQZ/b6hdZJ1TcrL8t1nh7kJl4k+Wg/BUY1w+5E2nMnL5RhwOKUZfMiN0TzSPL7nuYOMPblUpluUpRpHIcWzVM5tGl2MRNVKm8kNnQtDZSuEvLd8EhLa42yFhrUNmsOz2k18jv7NsQvROnUpLViYSPok4Kh6Ej592CcP/n3gTb+QHi+gRRVMoAmmcLqMCJXLFA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager