apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Ti
  nfs:
    server: 10.0.10.20
    path: /mnt/tank/k3s/immich-immich-library-pvc-0e33a02f-80e1-48a1-8e5a-f427c2984939
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 10Ti