apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.10.20
    path: /mnt/tank/k3s/downloads
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: qbittorrent-downloads
  resources:
    requests:
      storage: 10Ti