apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgAiO3gfD5pgNwoB8YSnKuz3rS/PfTyy20g+Wf8+c4tsA4Y3OVA05J5HFIpRSFF4VeQeNbxkx15pe5a43IpuSSwUxUCJcfKQuSt2lcYe+W5AmhpP8ss0hRG6aL2tCZW5G+R2dPisERO0raX9piF6KzcLEmwWXmMZg+EAo676HtkleY+RqMs52vg30yY30Uu2Obax3wmmyjMPMwliUVTKncxao3FvNIQO7SLuYqLTm14UnHdmdQ2XFOvpjFysJr0dYYMGsfJ40lv2UKisTqiDfWt6cDVLyGnmTLEWPUXpKtffrHW5aRc3E2AFuT5dRQ8j9up+4riwCYroWAEJL4UUvqpSGdGTpE6k2AbgOStB04xG/vvmgcTIHjJInMhd4QN19/7vo+EbUHjEDZSiCrFfzouaF4CfNllVNVTpayEZnXLXnjqzEEFbprNk3DQwIuL4WpJs8pt3u1xnQMIG1caD9e2h7ENZh4+mD4p60HbB7Z+dT+BuQlmXbyJKVYtMlVAeLjOAngVksG4yZpW9MhU7EkFFSM5N9IhyhY3oZtLNpI4H/5DY5K+EhPW9hRkI/C+7k6OiCm0gMfJRTCfkuLtxSMVHxJhpIUUBri31vVowG5CI9WizjHQkQoWubq++YgIW9BfTP0HECroBJ6mYp9l4B2yW+ciI3Zy+pI6Wpj8vxIdO+/DVIZrK9LaVU38Rndf8n0JltSjlqeSKq6cmwWXnXuoW+HAiEh0VHAVn6Rd9EIHsm9P5LVGbA1yTlQAs0Q==
  template:
    metadata:
      name: qbittorrent-vpn
      namespace: qbittorrent